// <auto-generated />
using System;
using Finance.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Finance.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191117031158_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Finance.Entity.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LetraId");

                    b.Property<string>("Nombre");

                    b.Property<int>("Tipo");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("LetraId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Finance.Entity.Letra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Denominacion");

                    b.Property<int>("DniGirado");

                    b.Property<string>("DniGirador");

                    b.Property<DateTime>("FechaGiro");

                    b.Property<DateTime>("FechaVencimiento");

                    b.Property<string>("FirmaGirador");

                    b.Property<string>("LugarGiro");

                    b.Property<string>("LugarPago");

                    b.Property<string>("NombreBeneficiario");

                    b.Property<string>("NombreGirado");

                    b.Property<string>("NombreGirador");

                    b.Property<double>("Retencion");

                    b.Property<int>("UserId");

                    b.Property<double>("ValorNominal");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Letras");
                });

            modelBuilder.Entity("Finance.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Password");

                    b.Property<string>("UrlImage");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Finance.Entity.Gasto", b =>
                {
                    b.HasOne("Finance.Entity.Letra", "Letra")
                        .WithMany("Gastos")
                        .HasForeignKey("LetraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Finance.Entity.Letra", b =>
                {
                    b.HasOne("Finance.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
